In [35]:
import sys
!{sys.executable} -m pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (2.2.6)
Requirement already satisfied: matplotlib in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (0.13.2)
Collecting scikit-learn
  Downloading scikit_learn-1.7.2-cp310-cp310-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (from matplotlib) (3.3.2)
Collecting scipy>=1.8.0 (from scikit-learn)
  Downloading scipy-1.15.3-cp310-cp310-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in c:\users\hp\onedrive\desktop\titanic\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading scikit_learn-1.7.2-cp310-cp310-win_amd64.whl (8.9 MB)
   ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.9 MB 2.2 MB/s eta 0:00:04
   ----- ---------------------------------- 1.3/8.9 MB 2.3 MB/s eta 0:00:04
   --------- ------------------------------ 2.1/8.9 MB 2.8 MB/s eta 0:00:03
   ------------ --------------------------- 2.9/8.9 MB 3.0 MB/s eta 0:00:03
   ----------------- ---------------------- 3.9/8.9 MB 3.4 MB/s eta 0:00:02
   ---------------------- ----------------- 5.0/8.9 MB 3.7 MB/s eta 0:00:02
   ---------------------------- ----------- 6.3/8.9 MB 4.1 MB/s eta 0:00:01
   ---------------------------------- ----- 7.6/8.9 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 8.9/8.9 MB 4.4 MB/s  0:00:02
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.15.3-cp310-cp310-win_amd64.whl (41.3 MB)
   ---------------------------------------- 0.0/41.3 MB ? eta -:--:--
   - -------------------------------------- 1.3/41.3 MB 6.7 MB/s eta 0:00:06
   -- ------------------------------------- 2.4/41.3 MB 6.4 MB/s eta 0:00:07
   --- ------------------------------------ 3.4/41.3 MB 5.6 MB/s eta 0:00:07
   ---- ----------------------------------- 4.2/41.3 MB 5.1 MB/s eta 0:00:08
   ---- ----------------------------------- 5.0/41.3 MB 4.7 MB/s eta 0:00:08
   ----- ---------------------------------- 5.8/41.3 MB 4.6 MB/s eta 0:00:08
   ------ --------------------------------- 6.3/41.3 MB 4.4 MB/s eta 0:00:08
   ------ --------------------------------- 7.1/41.3 MB 4.2 MB/s eta 0:00:09
   ------- -------------------------------- 7.9/41.3 MB 4.2 MB/s eta 0:00:08
   -------- ------------------------------- 8.7/41.3 MB 4.2 MB/s eta 0:00:08
   --------- ------------------------------ 9.4/41.3 MB 4.1 MB/s eta 0:00:08
   --------- ------------------------------ 10.2/41.3 MB 4.0 MB/s eta 0:00:08
   ---------- ----------------------------- 11.0/41.3 MB 4.0 MB/s eta 0:00:08
   ----------- ---------------------------- 11.8/41.3 MB 4.0 MB/s eta 0:00:08
   ------------ --------------------------- 12.6/41.3 MB 4.0 MB/s eta 0:00:08
   ------------ --------------------------- 13.4/41.3 MB 3.9 MB/s eta 0:00:08
   ------------- -------------------------- 13.9/41.3 MB 3.9 MB/s eta 0:00:08
   -------------- ------------------------- 14.7/41.3 MB 3.8 MB/s eta 0:00:07
   -------------- ------------------------- 15.5/41.3 MB 3.8 MB/s eta 0:00:07
   --------------- ------------------------ 16.0/41.3 MB 3.8 MB/s eta 0:00:07
   ---------------- ----------------------- 16.8/41.3 MB 3.8 MB/s eta 0:00:07
   ---------------- ----------------------- 17.3/41.3 MB 3.7 MB/s eta 0:00:07
   ----------------- ---------------------- 18.1/41.3 MB 3.7 MB/s eta 0:00:07
   ------------------ --------------------- 18.9/41.3 MB 3.7 MB/s eta 0:00:07
   ------------------- -------------------- 19.7/41.3 MB 3.7 MB/s eta 0:00:06
   -------------------- ------------------- 20.7/41.3 MB 3.7 MB/s eta 0:00:06
   -------------------- ------------------- 21.5/41.3 MB 3.8 MB/s eta 0:00:06
   --------------------- ------------------ 22.3/41.3 MB 3.8 MB/s eta 0:00:06
   ---------------------- ----------------- 23.3/41.3 MB 3.8 MB/s eta 0:00:05
   ----------------------- ---------------- 24.1/41.3 MB 3.8 MB/s eta 0:00:05
   ----------------------- ---------------- 24.6/41.3 MB 3.8 MB/s eta 0:00:05
   ------------------------ --------------- 25.4/41.3 MB 3.7 MB/s eta 0:00:05
   ------------------------- -------------- 26.0/41.3 MB 3.7 MB/s eta 0:00:05
   ------------------------- -------------- 26.7/41.3 MB 3.7 MB/s eta 0:00:04
   -------------------------- ------------- 27.5/41.3 MB 3.7 MB/s eta 0:00:04
   --------------------------- ------------ 28.3/41.3 MB 3.7 MB/s eta 0:00:04
   ---------------------------- ----------- 29.1/41.3 MB 3.7 MB/s eta 0:00:04
   ---------------------------- ----------- 29.9/41.3 MB 3.7 MB/s eta 0:00:04
   ----------------------------- ---------- 30.7/41.3 MB 3.7 MB/s eta 0:00:03
   ------------------------------ --------- 31.5/41.3 MB 3.7 MB/s eta 0:00:03
   ------------------------------- -------- 32.2/41.3 MB 3.7 MB/s eta 0:00:03
   -------------------------------- ------- 33.0/41.3 MB 3.7 MB/s eta 0:00:03
   --------------------------------- ------ 34.1/41.3 MB 3.7 MB/s eta 0:00:02
   --------------------------------- ------ 34.6/41.3 MB 3.7 MB/s eta 0:00:02
   ---------------------------------- ----- 35.7/41.3 MB 3.7 MB/s eta 0:00:02
   ----------------------------------- ---- 36.2/41.3 MB 3.7 MB/s eta 0:00:02
   ----------------------------------- ---- 36.7/41.3 MB 3.7 MB/s eta 0:00:02
   ------------------------------------ --- 37.2/41.3 MB 3.7 MB/s eta 0:00:02
   ------------------------------------ --- 37.7/41.3 MB 3.6 MB/s eta 0:00:01
   ------------------------------------- -- 38.3/41.3 MB 3.6 MB/s eta 0:00:01
   ------------------------------------- -- 38.8/41.3 MB 3.6 MB/s eta 0:00:01
   -------------------------------------- - 39.3/41.3 MB 3.6 MB/s eta 0:00:01
   -------------------------------------- - 40.1/41.3 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------  40.6/41.3 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------  41.2/41.3 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 41.3/41.3 MB 3.5 MB/s  0:00:11
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------------------------------------- 0/4 [threadpoolctl]
   ---------------------------------------- 0/4 [threadpoolctl]
   ---------------------------------------- 0/4 [threadpoolctl]
   ---------------------------------------- 0/4 [threadpoolctl]
   ---------------------------------------- 0/4 [threadpoolctl]
   ---------------------------------------- 0/4 [threadpoolctl]
   ---------------------------------------- 0/4 [threadpoolctl]
   ---------------------------------------- 0/4 [threadpoolctl]
   ---------------------------------------- 0/4 [threadpoolctl]
   ---------------------------------------- 0/4 [threadpoolctl]
   ---------------------------------------- 0/4 [threadpoolctl]
   ---------------------------------------- 0/4 [threadpoolctl]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
print ("hi")

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

hi

KeyboardInterrupt:

In [8]:
print("hi")

hi

In [12]:
train_df = pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\titanic\\dataset\\train.csv")
test_df = pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\titanic\\dataset\\test.csv")

In [14]:
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
train_df.shape

(418, 11)

In [23]:
train_df.info()
train_df.isnull().sum()
train_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [25]:
features=["Pclass","Sex","SibSp","Parch","Embarked"]
x=train_df[features]
y=train_df["Survived"]

x_test=test_df[features]

In [30]:
x.head()
y.head()
#x_test.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64